### ISSUE TITLE
cannot start program

### ISSUE THREAD

**Issue by ghost** [andreasBihlmaier/pysdf#13]
Hi there, 

I am getting the error 

> Traceback (most recent call last):
  File "/Users/++++/pysdf/scripts/sdf2urdf.py", line 6, in <module>
    import pysdf
  File "/Users/++++/opt/anaconda3/lib/python3.7/site-packages/pysdf/__init__.py", line 1, in <module>
    from parse import SDF, homogeneous2translation_quaternion, homogeneous2pose_msg, sdf2tfname, models_paths
ImportError: cannot import name 'SDF' from 'parse' (/Users/++++/opt/anaconda3/lib/python3.7/site-packages/parse.py)

Any idea on the cause?

**Comment by andreasBihlmaier** [comment]
How did you install pysdf?
Given the paths in the error message, I would assume it was not through catkin(?)

**Comment by ghost** [comment]
is it possible to use this package without ros and anything? just sdf2urdf?

**Comment by andreasBihlmaier** [comment]
pysdf depends on `tf.transformations` and `geometry_msgs.msg` which are both provided by core ROS packages. Yes, you can install them (and their dependencies) without installing a full ROS distribution, but it might require some effort to get everything working.
