### ISSUE TITLE
ImportError: cannot import name 'SDF' from 'parse'

### ISSUE THREAD

**Issue by FioreViola** [andreasBihlmaier/pysdf#14]
Hello,

I am a robotics student trying to use this code and I am running into a similar issue as another error listed, except I am using this in ROS and it was installed in my catkin_ws/src area. I am new to ROS and was hoping to see if you could help me understand what this error is and how to fix it if you have time. I know that anaconda/ROS don't play well and it seems to be trying to use the parse python module from anaconda instead of the parse.py provided in your package. Any help or guidance would be greatly appreciated, I tried googling but couldn't find cases like this one. 

I am running ROS melodic on Ubuntu Bionic 18.04 and do have anaconda3 installed as well for other projects I am working on (non ROS). I have tried commenting out the anaconda3/bin file path in my .bashrc file but that doesn't seem to fix it either. Thank you once again for any help you can provide. 

Kind regards,
Heather

![Screenshot from 2020-11-22 10-13-31](https://user-images.githubusercontent.com/74867764/99907612-ca4ce980-2cab-11eb-993c-f5edca9e62db.png)

**Comment by andreasBihlmaier** [comment]
Hi @FioreViola, were you able to solve the issue?
The last line in the error seems to indicate that a wrong file, also called parse.py, is loaded instead of pysdf/parse.py.

**Comment by FioreViola** [comment]
Thank you for reaching out I was able to solve the issue by creating a new
development environment (using anaconda and ROS causes some weird python
path issues). Creating a new environment without anaconda caused the code
to work perfectly. Thank you and have a great weekend!

**Comment by andreasBihlmaier** [comment]
Thank you for the answer. Good to hear!
